In [ ]:
#Formulas y usos de numpy

import numpy as np

In [4]:
#Crear un arreglo de 1 dimensión con 5 elementos

arr1d = np.array([10, 20, 30, 40, 50, 60])

print("Arreglo de 1 dimensión: ", arr1d)
print("Forma del arreglo: ", arr1d.shape)
print("Tipo de datos del arreglo: ", arr1d.dtype)


Arreglo de 1 dimensión:  [10 20 30 40 50 60]
Forma del arreglo:  (6,)
Tipo de datos del arreglo:  int64


In [5]:
#Cambiar la forma del arreglo a 2 dimensiones (2 filas y 3 columnas)
arr2d = arr1d.reshape(2, 3)
print("Arreglo de 2 dimensiones:\n", arr2d)
print("Nueva forma del arreglo: ", arr2d.shape)
print("Tipo de datos del arreglo: ", arr2d.dtype)



Arreglo de 2 dimensiones:
 [[10 20 30]
 [40 50 60]]
Nueva forma del arreglo:  (2, 3)
Tipo de datos del arreglo:  int64


In [6]:
#Crear una matriz con forma de 4 filas y 4 columnas con numeros aleatorios entre 0 y 1

matrix = np.random.rand(4, 4)
print("Arreglo de 4x4 con numeros aleatorios entre 0 y 1:\n", matrix)
print("Nueva forma del arreglo: ", matrix.shape)
print("Tipo de datos del arreglo: ", matrix.dtype)



Arreglo de 4x4 con numeros aleatorios entre 0 y 1:
 [[0.18444694 0.42885256 0.49802412 0.03324152]
 [0.87941427 0.24473834 0.37921876 0.71479482]
 [0.96393488 0.01408679 0.30586548 0.16121775]
 [0.9086826  0.46995547 0.33158214 0.22877475]]
Nueva forma del arreglo:  (4, 4)
Tipo de datos del arreglo:  float64


In [10]:
#Crear un arreglo de 2 dimensiones a partir de una lista de listas

arr= np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(arr, type (arr))

[[1 2 3]
 [4 5 6]
 [7 8 9]] <class 'numpy.ndarray'>


In [11]:
#Crear un arreglo de ceros con una forma de (3,4)

arr =np.zeros((3,4))
print(arr)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [16]:
#Crear un arreglo con unos con una forma de (2,2)
array =np.ones((2,2))
array

array([[1., 1.],
       [1., 1.]])

In [17]:
#Crear una matriz identidad de tamaño 3x3
arr =np.eye(4)
print(arr)


[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [19]:
#Crear un arreglo 3d de ceros con forma (2,3,4)
arr = np.zeros((2,3,4)) #2-->Cantidad de matrices, 3-->Filas, 4-->Columnas
arr[0, 1, 2] = 5 #Asignar el valor 5 a la posición [0,1,2]
print(arr)

[[[0. 0. 0. 0.]
  [0. 0. 5. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]]


In [ ]:
#Transponer una matriz
arr.T 
#Es como cambiar el eje de las filas a columnas y viceversa

array([[[0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [5., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.]]])

In [23]:
#Combinar arreglos 
arr1 = np.array([[1,2], [3,4]])
arr2 = np.array([[5,6], [7,8]])
arr1, arr2

(array([[1, 2],
        [3, 4]]),
 array([[5, 6],
        [7, 8]]))

In [24]:
#Concatenar los arreglos horizontalmente
arr_h =np.hstack((arr1, arr2))
arr_h

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

In [25]:
#Concatenar los arreglos vertical
arr_v =np.vstack((arr1, arr2))
arr_v

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [28]:
#Operaciones matematicas con numpy

arr = np.array([1,2,3,4, 5])
arr 

array([1, 2, 3, 4, 5])

In [29]:
#Suma de arreglos
arr_sum = np.sum(arr)
arr_sum


np.int64(15)

In [30]:
#Promedio de los elementos del arreglo
arr_mean = np.mean(arr)
arr_mean

np.float64(3.0)

In [31]:
#Mediana de los elementos del arreglo

arr_median = np.median(arr)
arr_median

np.float64(3.0)

In [32]:
#Producto de los elementos del arreglo

arr_product = np.prod(arr)
arr_product

np.int64(120)

In [33]:
#Desviacion estandar de los elementos del arreglo
arr_desv= np.std(arr)
arr_desv

np.float64(1.4142135623730951)

In [34]:
#Varianza
arr_var= np.var(arr)
arr_var

np.float64(2.0)

In [35]:
#Minimo y maximo de los elementos

arr_min =np.min(arr)
arr_max =np.max(arr)

arr_min, arr_max

(np.int64(1), np.int64(5))

In [36]:
#Calcular la suma acumulativa
arr_cumsum = np.cumsum(arr)
arr_cumsum

array([ 1,  3,  6, 10, 15])

In [ ]:
#Operaciones vectoriales u operaciones elemento a elemento
#Suma de arreglos elemento a elementos
arr + arr 


array([ 2,  4,  6,  8, 10])

In [ ]:
#Resta de arreglos elemento a elemento
arr - arr

array([0, 0, 0, 0, 0])

In [39]:
#División de arreglos elemento a elemento

arr /arr

array([1., 1., 1., 1., 1.])

In [40]:
#Multiplicación de arreglos elemento a elemento
arr * arr

array([ 1,  4,  9, 16, 25])